### ISSUE TITLE
When i pass a certain depth, i get teleported back to the surface, its probabaly my fault

### ISSUE THREAD

**Issue by BoringKobold** [daniellovell/deepmine#3]
Title says it

**Comment by daniellovell** [comment]
Hi Kobold, this typically happens when you're playing a server where the host has the mod and you do not have the mod. Could this be the case?
Can you confirm that you can reproduce this bug in singleplayer with the mod installed?

**Comment by BoringKobold** [comment]
I do have the mod, my friendcould pass that depth just fine other than I would see him warp to the surface and just fly throigh the ground to where he should be and the mod works fine, it just acts like the original bedrock layer is still there, we lowered the bedrock depth in the settings and now I can go pass that depth perfectly fine, I dont know what's going with the teleporting to the surface, it's possible I installed the mod wrong, but for now, it works, if I encounter that issue again, I'll let you know, cheers.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by daniellovell** [comment]
Thanks for letting me know how it was resolved. Going to make a note that lowering bedrock depth in the config fixes this issue and close it :-)
