### ISSUE TITLE
Stopped working yesterday (6/2/2022)

### ISSUE THREAD

**Issue by tdierickx** [daniellovell/deepmine#9]
I'd been playing the beta for a few weeks with this mod loaded and it'd been working great ... until sometime yesterday with one of the several flurry of beta updates they did yesterday. Suddenly, I went into load my saved game and my pre-existing deep tunnel I had with all kinds of rich ores (thanks to this mod) looked like lava and whenever I tried going down it teleported me back to the surface.

Using the GPS tool and creating a new hole, I saw it was only letting me go down -40 again. I also could no longer stack ores >50 like I could when this mod was working.

I was able to manually edit my save game "world.xml" to force <BedrockLevel>-160</BedrockLevel> and could t then go down without being teleported but still looked lava-ish and ore values were back to surface-level values (and could not stack >50) 

I'm guessing 0.2.3293.16399 broke it. Now that they updated the stable branch from the beta branch it's still not working either. Whatever they did yesterday to "improve" the beta and then the stable release breaks this mod. 

I love this mod. I can't play without it. I just can't! :-)

**Comment by daniellovell** [comment]
Hiya @tdierickx thanks for your kind words about the mod :) 
I’m aware that the rework of the codebase from the Rocketwerkz team broke the latest release of the mod.
I have a pre-release branch here from a month or so ago that should support the rework
 https://github.com/daniellovell/deepmine/releases/tag/v0.2.3-beta

Please give it a try and do let me know if it works with the latest update, and I’ll move it to an official release state 

cheers

**Comment by tdierickx** [comment]
Thanks for the quick reply! That's the one I have been using and was working until one of the very most recent beta releases the other night the day before they pushed to stable. Previous beta versions up to that point were working. 

One thing I do notice though: the DeepMineMod.dll file contained within the "deepmine-v0.2.3-beta.zip" release looks like its from 7/2/2021 ? Shouldn't it really be from April 2022?

**Comment by ThatBeADragon** [comment]
To fix some of this, I managed to recompile this by renaming Mineables to Minables in Patches.cs and removing the com.unity.multiplayer-hlapi.runtime.dll reference, as this is no longer part of Stationeers. Also for the stack size this bit I had to comment out for now, as how this is done in the game code is now different, but I haven't yet identified where its changed to so I'm not clear how to fix this yet.

**Comment by ThatBeADragon** [comment]
Further to this I have fixed the ore stack sizes as well and have submitted a pull request with the changes to allow this to be compiled and run on Stationeers 0.2.3304.16432.

**Comment by tdierickx** [comment]
FYI: I couldn't take it anymore, I attempted to compile the mod myself following ThatBeADragon's code requested changes and it works! Thank you!!

p.s. looks like I'm on Stationeers 0.2.3344.16555
